name: image_pixels
description: Lets you extend the background color of an image, or else build any widget that depends on the image width/height, and the color of its pixels.
version: 1.0.2
author: Marcelo Glasberg <marcglasberg@gmail.com>
homepage: https://github.com/marcglasberg/image_pixels

environment:
  sdk: ">=2.8.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
